* Browse the Emacsmirror package database

This package provides access to a local copy of the [[https://emacsmirror.net][Emacsmirror]]
package database.  It provides low-level functions for querying the
database and a ~package.el~-like user interface for browsing the
available packages.

The Emacsmirror is a growing collection of Emacs Lisp packages.  All
mirrored packages are available as Git repositories.  In most cases
this is done by mirroring the upstream Git repository, but if upstream
uses something else, then the mirror nevertheless makes the package
available as a Git repository.

One primary purpose of the Emacsmirror is to provide a comprehensive
list of available Emacs packages, including packages which have gone
out of fashion (but might later prove to be useful still).

For more information see the [[https://emacsmirror.net/manual/epkg][manual]] and the [[https://emacsmirror.net][Emacsmirror]].

#+html: <br><br>
#+html: <a href="https://github.com/emacscollective/epkg/actions/workflows/compile.yml"><img alt="Compile" src="https://github.com/emacscollective/epkg/actions/workflows/compile.yml/badge.svg"/></a>
#+html: <a href="https://github.com/emacscollective/epkg/actions/workflows/manual.yml"><img alt="Manual" src="https://github.com/emacscollective/epkg/actions/workflows/manual.yml/badge.svg"/></a>
#+html: <a href="https://stable.melpa.org/#/epkg"><img alt="MELPA Stable" src="https://stable.melpa.org/packages/epkg-badge.svg"/></a>
#+html: <a href="https://melpa.org/#/epkg"><img alt="MELPA" src="https://melpa.org/packages/epkg-badge.svg"/></a>
